### PR TITLE
back and side fix for form resubmission on reload

### PR DESCRIPTION
**Pull request by cyriliser**

### CODE REVIEW

**Comment by NhlalukoG** [comment]
The use of api prevented form reloading. This was fixed for admin and user login and registration on the last pull request I made.

Its caused by submitting forms to the same page. Security wise it should be done. If the form can be read by apache that means it can be pulled meaning all our queries could end up visible to hackers.

**Comment by NhlalukoG** [comment]
api directory permissions would be limited to executable only no read or write by apache. that would ensure that no user/hacker can pull the documents. but leaving the form processing logic on the same documents as the submit area is dangerous.

**Review by NhlalukoG — CHANGES_REQUESTED** [review]
Check my other comments

**Comment by NhlalukoG** [comment]
but if its all good then merge.

**Review by cyriliser — COMMENTED** [review]
commented out the function call on api/register.php

**Pull request merged**
